services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
    image: superhero-frontend:latest
    ports:
      - "5173:80"
    restart: unless-stopped
